sudo: required

language: node_js
node_js:
  - node

before_install:
  - openssl aes-256-cbc -K $encrypted_1e675daaeb1c_key -iv $encrypted_1e675daaeb1c_iv -in ./keys/travis-service-account.json.enc -out ./keys/travis-service-account.json -d

install:
  - cd client && npm install && cd ..
  - cd server && npm install && cd ..

script:
  - npm run test

before_deploy:
  - cd client && npm run build && cd ..

deploy:
  - provider: gae
    project: tekktekk-notes
    keyfile: ./keys/travis-service-account.json
    config: "dispatch.yaml"
    verbosity: debug
    skip_cleanup: true
    on: master

  - provider: gae
    project: tekktekk-notes
    keyfile: ./keys/travis-service-account.json
    config: "./client/prod.yaml"
    verbosity: debug
    skip_cleanup: true
    on: master

  - provider: gae
    project: tekktekk-notes
    keyfile: ./keys/travis-service-account.json
    config: "./server/prod.yaml"
    verbosity: debug
    skip_cleanup: true
    on: master

  - provider: gae
    project: tekktekk-notes
    keyfile: ./keys/travis-service-account.json
    config: "dispatch.yaml"
    verbosity: debug
    skip_cleanup: true
    on: dev

  - provider: gae
    project: tekktekk-notes
    keyfile: ./keys/travis-service-account.json
    config: "./client/dev.yaml"
    verbosity: debug
    skip_cleanup: true
    on: dev

  - provider: gae
    project: tekktekk-notes
    keyfile: ./keys/travis-service-account.json
    config: "./server/dev.yaml"
    verbosity: debug
    skip_cleanup: true
    on: dev
